-- Seed Data for Barangay Equipment Borrowing System
-- At least 20 rows per master table, 30+ rows in transactional table
-- Run each INSERT statement separately in Access Query Editor

-- Insert Equipment (20+ items)
INSERT INTO Equipment (ItemName, Category, Description, Stock, Unit, CreatedAt, UpdatedAt) VALUES ('Folding Chair', 'Furniture', 'Plastic folding chair, white', 50, 'pcs', NOW(), NOW());
INSERT INTO Equipment (ItemName, Category, Description, Stock, Unit, CreatedAt, UpdatedAt) VALUES ('Folding Chair', 'Furniture', 'Plastic folding chair, blue', 30, 'pcs', NOW(), NOW());
INSERT INTO Equipment (ItemName, Category, Description, Stock, Unit, CreatedAt, UpdatedAt) VALUES ('Round Table', 'Furniture', '8-seater round table', 15, 'pcs', NOW(), NOW());
INSERT INTO Equipment (ItemName, Category, Description, Stock, Unit, CreatedAt, UpdatedAt) VALUES ('Rectangular Table', 'Furniture', '10-seater rectangular table', 20, 'pcs', NOW(), NOW());
INSERT INTO Equipment (ItemName, Category, Description, Stock, Unit, CreatedAt, UpdatedAt) VALUES ('10x10 Tent', 'Tent', '10x10 feet event tent, blue', 8, 'pcs', NOW(), NOW());
INSERT INTO Equipment (ItemName, Category, Description, Stock, Unit, CreatedAt, UpdatedAt) VALUES ('10x20 Tent', 'Tent', '10x20 feet event tent, blue', 5, 'pcs', NOW(), NOW());
INSERT INTO Equipment (ItemName, Category, Description, Stock, Unit, CreatedAt, UpdatedAt) VALUES ('Sound System', 'Electronics', 'Complete PA system with 2 speakers', 2, 'set', NOW(), NOW());
INSERT INTO Equipment (ItemName, Category, Description, Stock, Unit, CreatedAt, UpdatedAt) VALUES ('Microphone', 'Electronics', 'Wireless microphone', 4, 'pcs', NOW(), NOW());
INSERT INTO Equipment (ItemName, Category, Description, Stock, Unit, CreatedAt, UpdatedAt) VALUES ('Generator', 'Equipment', '5KVA portable generator', 3, 'pcs', NOW(), NOW());
INSERT INTO Equipment (ItemName, Category, Description, Stock, Unit, CreatedAt, UpdatedAt) VALUES ('Extension Cord', 'Electronics', '50-meter extension cord', 10, 'pcs', NOW(), NOW());
INSERT INTO Equipment (ItemName, Category, Description, Stock, Unit, CreatedAt, UpdatedAt) VALUES ('Spotlight', 'Electronics', 'Portable spotlight', 6, 'pcs', NOW(), NOW());
INSERT INTO Equipment (ItemName, Category, Description, Stock, Unit, CreatedAt, UpdatedAt) VALUES ('Barricade', 'Safety', 'Metal barricade, orange', 25, 'pcs', NOW(), NOW());
INSERT INTO Equipment (ItemName, Category, Description, Stock, Unit, CreatedAt, UpdatedAt) VALUES ('Traffic Cone', 'Safety', 'Orange traffic cone', 40, 'pcs', NOW(), NOW());
INSERT INTO Equipment (ItemName, Category, Description, Stock, Unit, CreatedAt, UpdatedAt) VALUES ('Rope', 'General', 'Nylon rope, 50 meters', 15, 'pcs', NOW(), NOW());
INSERT INTO Equipment (ItemName, Category, Description, Stock, Unit, CreatedAt, UpdatedAt) VALUES ('Tarpaulin', 'General', 'Waterproof tarpaulin, 10x12', 12, 'pcs', NOW(), NOW());
INSERT INTO Equipment (ItemName, Category, Description, Stock, Unit, CreatedAt, UpdatedAt) VALUES ('Cooler', 'General', 'Large ice cooler', 5, 'pcs', NOW(), NOW());
INSERT INTO Equipment (ItemName, Category, Description, Stock, Unit, CreatedAt, UpdatedAt) VALUES ('Water Dispenser', 'General', 'Electric water dispenser', 3, 'pcs', NOW(), NOW());
INSERT INTO Equipment (ItemName, Category, Description, Stock, Unit, CreatedAt, UpdatedAt) VALUES ('Step Ladder', 'Equipment', '5-step aluminum ladder', 4, 'pcs', NOW(), NOW());
INSERT INTO Equipment (ItemName, Category, Description, Stock, Unit, CreatedAt, UpdatedAt) VALUES ('Tool Box', 'Equipment', 'Basic tool set', 6, 'pcs', NOW(), NOW());
INSERT INTO Equipment (ItemName, Category, Description, Stock, Unit, CreatedAt, UpdatedAt) VALUES ('First Aid Kit', 'Safety', 'Complete first aid kit', 8, 'pcs', NOW(), NOW());
INSERT INTO Equipment (ItemName, Category, Description, Stock, Unit, CreatedAt, UpdatedAt) VALUES ('Tarp Cover', 'General', 'Heavy duty tarp cover', 10, 'pcs', NOW(), NOW());
INSERT INTO Equipment (ItemName, Category, Description, Stock, Unit, CreatedAt, UpdatedAt) VALUES ('Portable Fan', 'Electronics', 'Standing electric fan', 7, 'pcs', NOW(), NOW());

-- Insert Borrowers (20+ borrowers)
INSERT INTO Borrowers (FullName, ContactNo, Address, Email, CreatedAt, UpdatedAt) VALUES ('Juan Dela Cruz', '09171234567', '123 Rizal Street, Barangay Centro', 'juan.delacruz@email.com', NOW(), NOW());
INSERT INTO Borrowers (FullName, ContactNo, Address, Email, CreatedAt, UpdatedAt) VALUES ('Maria Santos', '09223456789', '456 Mabini Avenue, Barangay Centro', 'maria.santos@email.com', NOW(), NOW());
INSERT INTO Borrowers (FullName, ContactNo, Address, Email, CreatedAt, UpdatedAt) VALUES ('Pedro Garcia', '09334567890', '789 Bonifacio Street, Barangay Norte', 'pedro.garcia@email.com', NOW(), NOW());
INSERT INTO Borrowers (FullName, ContactNo, Address, Email, CreatedAt, UpdatedAt) VALUES ('Ana Lopez', '09445678901', '321 Aguinaldo Road, Barangay Sur', 'ana.lopez@email.com', NOW(), NOW());
INSERT INTO Borrowers (FullName, ContactNo, Address, Email, CreatedAt, UpdatedAt) VALUES ('Carlos Rodriguez', '09556789012', '654 Quezon Boulevard, Barangay Este', 'carlos.rodriguez@email.com', NOW(), NOW());
INSERT INTO Borrowers (FullName, ContactNo, Address, Email, CreatedAt, UpdatedAt) VALUES ('Rosa Martinez', '09667890123', '987 Roxas Street, Barangay Oeste', 'rosa.martinez@email.com', NOW(), NOW());
INSERT INTO Borrowers (FullName, ContactNo, Address, Email, CreatedAt, UpdatedAt) VALUES ('Jose Fernandez', '09778901234', '147 Lapu-Lapu Avenue, Barangay Norte', 'jose.fernandez@email.com', NOW(), NOW());
INSERT INTO Borrowers (FullName, ContactNo, Address, Email, CreatedAt, UpdatedAt) VALUES ('Carmen Reyes', '09889012345', '258 Paterno Street, Barangay Sur', 'carmen.reyes@email.com', NOW(), NOW());
INSERT INTO Borrowers (FullName, ContactNo, Address, Email, CreatedAt, UpdatedAt) VALUES ('Antonio Cruz', '09990123456', '369 Luna Road, Barangay Centro', 'antonio.cruz@email.com', NOW(), NOW());
INSERT INTO Borrowers (FullName, ContactNo, Address, Email, CreatedAt, UpdatedAt) VALUES ('Lourdes Torres', '09101234567', '741 Magsaysay Boulevard, Barangay Norte', 'lourdes.torres@email.com', NOW(), NOW());
INSERT INTO Borrowers (FullName, ContactNo, Address, Email, CreatedAt, UpdatedAt) VALUES ('Roberto Ramos', '09212345678', '852 Gomez Street, Barangay Este', 'roberto.ramos@email.com', NOW(), NOW());
INSERT INTO Borrowers (FullName, ContactNo, Address, Email, CreatedAt, UpdatedAt) VALUES ('Sofia Villanueva', '09323456789', '963 Del Pilar Avenue, Barangay Oeste', 'sofia.villanueva@email.com', NOW(), NOW());
INSERT INTO Borrowers (FullName, ContactNo, Address, Email, CreatedAt, UpdatedAt) VALUES ('Ricardo Mendoza', '09434567890', '159 Rizal Street, Barangay Sur', 'ricardo.mendoza@email.com', NOW(), NOW());
INSERT INTO Borrowers (FullName, ContactNo, Address, Email, CreatedAt, UpdatedAt) VALUES ('Elena Castro', '09545678901', '357 Mabini Avenue, Barangay Centro', 'elena.castro@email.com', NOW(), NOW());
INSERT INTO Borrowers (FullName, ContactNo, Address, Email, CreatedAt, UpdatedAt) VALUES ('Felipe Aquino', '09656789012', '468 Bonifacio Street, Barangay Norte', 'felipe.aquino@email.com', NOW(), NOW());
INSERT INTO Borrowers (FullName, ContactNo, Address, Email, CreatedAt, UpdatedAt) VALUES ('Isabela De Leon', '09767890123', '579 Aguinaldo Road, Barangay Este', 'isabela.deleon@email.com', NOW(), NOW());
INSERT INTO Borrowers (FullName, ContactNo, Address, Email, CreatedAt, UpdatedAt) VALUES ('Manuel Bautista', '09878901234', '680 Quezon Boulevard, Barangay Oeste', 'manuel.bautista@email.com', NOW(), NOW());
INSERT INTO Borrowers (FullName, ContactNo, Address, Email, CreatedAt, UpdatedAt) VALUES ('Teresa Morales', '09989012345', '791 Roxas Street, Barangay Sur', 'teresa.morales@email.com', NOW(), NOW());
INSERT INTO Borrowers (FullName, ContactNo, Address, Email, CreatedAt, UpdatedAt) VALUES ('Alfredo Gutierrez', '09190123456', '802 Lapu-Lapu Avenue, Barangay Centro', 'alfredo.gutierrez@email.com', NOW(), NOW());
INSERT INTO Borrowers (FullName, ContactNo, Address, Email, CreatedAt, UpdatedAt) VALUES ('Consuelo Herrera', '09201234567', '913 Paterno Street, Barangay Norte', 'consuelo.herrera@email.com', NOW(), NOW());
INSERT INTO Borrowers (FullName, ContactNo, Address, Email, CreatedAt, UpdatedAt) VALUES ('Miguel Ocampo', '09312345678', '124 Luna Road, Barangay Este', 'miguel.ocampo@email.com', NOW(), NOW());
INSERT INTO Borrowers (FullName, ContactNo, Address, Email, CreatedAt, UpdatedAt) VALUES ('Rosario Alvarado', '09423456789', '235 Magsaysay Boulevard, Barangay Oeste', 'rosario.alvarado@email.com', NOW(), NOW());

-- Insert Borrowings (30+ transactions)
-- Note: In Access, dates use #YYYY-MM-DD# format
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (1, #2024-01-15#, #2024-01-17#, #2024-01-17#, 'Returned', 'Community meeting', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (2, #2024-01-18#, #2024-01-20#, #2024-01-20#, 'Returned', 'Birthday party', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (3, #2024-01-20#, #2024-01-22#, NULL, 'Active', 'Wedding reception', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (4, #2024-01-22#, #2024-01-24#, #2024-01-23#, 'Returned', 'Family gathering', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (5, #2024-01-25#, #2024-01-27#, NULL, 'Active', 'Barangay fiesta', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (6, #2024-02-01#, #2024-02-03#, #2024-02-03#, 'Returned', 'School event', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (7, #2024-02-05#, #2024-02-07#, #2024-02-08#, 'Returned', 'Delayed return', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (8, #2024-02-08#, #2024-02-10#, NULL, 'Active', 'Medical mission', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (9, #2024-02-12#, #2024-02-14#, #2024-02-14#, 'Returned', 'Valentine event', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (10, #2024-02-15#, #2024-02-17#, #2024-02-16#, 'Returned', 'Community cleanup', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (11, #2024-02-18#, #2024-02-20#, NULL, 'Active', 'Sports event', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (12, #2024-02-20#, #2024-02-22#, #2024-02-22#, 'Returned', 'Religious gathering', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (13, #2024-02-25#, #2024-02-27#, #2024-02-27#, 'Returned', 'Seminar', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (14, #2024-03-01#, #2024-03-03#, NULL, 'Active', 'Food distribution', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (15, #2024-03-05#, #2024-03-07#, #2024-03-06#, 'Returned', 'Health fair', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (16, #2024-03-08#, #2024-03-10#, #2024-03-10#, 'Returned', 'Cultural show', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (17, #2024-03-12#, #2024-03-14#, NULL, 'Active', 'Job fair', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (18, #2024-03-15#, #2024-03-17#, #2024-03-17#, 'Returned', 'Cleanup drive', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (19, #2024-03-18#, #2024-03-20#, #2024-03-19#, 'Returned', 'Early return', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (20, #2024-03-20#, #2024-03-22#, NULL, 'Active', 'Graduation ceremony', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (1, #2024-03-22#, #2024-03-24#, #2024-03-24#, 'Returned', 'Second borrowing', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (2, #2024-03-25#, #2024-03-27#, NULL, 'Active', 'Anniversary celebration', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (3, #2024-03-28#, #2024-03-30#, #2024-03-30#, 'Returned', 'Family reunion', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (4, #2024-04-01#, #2024-04-03#, NULL, 'Active', 'Easter event', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (5, #2024-04-05#, #2024-04-07#, #2024-04-07#, 'Returned', 'Community meeting', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (6, #2024-04-08#, #2024-04-10#, #2024-04-09#, 'Returned', 'School program', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (7, #2024-04-12#, #2024-04-14#, NULL, 'Active', 'Fundraising event', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (8, #2024-04-15#, #2024-04-17#, #2024-04-17#, 'Returned', 'Health program', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (9, #2024-04-18#, #2024-04-20#, NULL, 'Active', 'Sports tournament', NOW(), NOW());
INSERT INTO Borrowings (BorrowerID, BorrowDate, ExpectedReturnDate, ActualReturnDate, Status, Notes, CreatedAt, UpdatedAt) VALUES (10, #2024-04-22#, #2024-04-24#, #2024-04-24#, 'Returned', 'Community assembly', NOW(), NOW());

-- Insert BorrowingItems (detail records for borrowings)
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (1, 1, 20, 20, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (1, 5, 2, 2, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (2, 1, 15, 15, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (2, 3, 3, 3, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (3, 1, 30, 0, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (3, 4, 5, 0, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (3, 5, 3, 0, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (4, 2, 25, 25, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (4, 5, 1, 1, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (5, 1, 40, 0, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (5, 3, 8, 0, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (5, 5, 5, 0, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (5, 7, 1, 0, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (6, 1, 18, 18, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (6, 3, 4, 4, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (7, 2, 20, 20, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (7, 4, 3, 3, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (7, 6, 2, 2, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (8, 1, 25, 0, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (8, 5, 2, 0, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (9, 1, 12, 12, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (9, 3, 2, 2, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (10, 1, 15, 15, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (10, 12, 10, 10, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (11, 1, 20, 0, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (11, 3, 4, 0, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (12, 1, 18, 18, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (12, 5, 1, 1, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (13, 1, 22, 22, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (13, 3, 5, 5, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (14, 1, 30, 0, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (14, 4, 6, 0, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (15, 1, 15, 15, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (15, 5, 2, 2, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (16, 1, 20, 20, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (16, 3, 4, 4, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (17, 1, 25, 0, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (17, 5, 3, 0, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (18, 1, 18, 18, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (18, 12, 8, 8, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (19, 1, 16, 16, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (19, 3, 3, 3, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (20, 1, 35, 0, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (20, 3, 7, 0, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (20, 5, 4, 0, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (21, 1, 15, 15, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (21, 5, 1, 1, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (22, 1, 20, 0, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (22, 4, 4, 0, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (23, 1, 18, 18, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (23, 3, 3, 3, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (24, 1, 25, 0, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (24, 5, 2, 0, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (25, 1, 20, 20, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (25, 3, 4, 4, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (26, 1, 16, 16, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (26, 5, 1, 1, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (27, 1, 22, 0, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (27, 4, 5, 0, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (28, 1, 18, 18, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (28, 5, 2, 2, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (29, 1, 24, 0, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (29, 3, 5, 0, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (30, 1, 20, 20, NOW(), NOW());
INSERT INTO BorrowingItems (BorrowingID, EquipmentID, Quantity, ReturnedQuantity, CreatedAt, UpdatedAt) VALUES (30, 5, 1, 1, NOW(), NOW());
